### ISSUE TITLE
why do u drinking the alcohol

### ISSUE THREAD

**Issue by halal-beef** [HiImMilan/NyankoScript#1]

**Comment by TheMorc** [comment]
![caption_29](https://github.com/HiImMilan/NyankoScript/assets/13377926/7b1b5d53-262f-454d-83be-fc71afd0853a)

**Comment by HiImMilan** [comment]
this concludes our debate.

**Comment by halal-beef** [comment]
![image](https://github.com/HiImMilan/NyankoScript/assets/78730004/c14bd998-8dec-43d7-8f5f-30344ef99347)

**Comment by bulldozer548** [comment]
> ![image](https://user-images.githubusercontent.com/78730004/265552761-c14bd998-8dec-43d7-8f5f-30344ef99347.png)

![trol](https://upload.wikimedia.org/wikipedia/en/9/9a/Trollface_non-free.png)

**Comment by bulldozer548** [comment]
![Trollface_non-free](https://github.com/HiImMilan/NyankoScript/assets/5161014/a475099b-7c26-4666-9ef9-86835fb2c6bc)

**Comment by halal-beef** [comment]
![Screenshot_20230902-224850_TikTok](https://github.com/HiImMilan/NyankoScript/assets/78730004/f8c457cc-94fd-4303-9d65-99617fb2d36f)

**Comment by halal-beef** [comment]
Remember Milan censoring the proof won't get you anywhere
